server:
  servlet:
    context-path: /Client-Address

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  datasource:
    url: jdbc:h2:mem:demodb
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
